### ISSUE TITLE
Autoload backlog instead of "show more" button

### ISSUE THREAD

**Issue by bews** [thelounge/lounge#1131] opened 2017-05-03 07:06 UTC
History should automatically load when scrolling up. I think it may be easy to implement.

**Comment by MiniDigger** [comment] 2017-05-03 07:16
duplicate of #207

**Closed** 2017-05-03 08:02 UTC

**Comment by astorije** [comment] 2017-05-03 11:15
> History should automatically load when scrolling up.

Ahah, famous last words 😄
I did say the same thing then attempted it in https://github.com/thelounge/lounge/pull/1038 then gave up.
