### ISSUE TITLE
Add Support for Client Certificates

### ISSUE THREAD

**Issue by Verequies** [thelounge/lounge#865] opened 2017-01-03 00:38 UTC
Would be great if support for client certificates were added. You could possibly do it similarly to how it is done in the web IRC client called dispatch [https://github.com/khlieng/dispatch](https://github.com/khlieng/dispatch). 

However for mobiles, this maybe a tad difficult (Android might be okay), so perhaps on desktop, the ability is always enabled, however on mobile you can only use client certificates if you add them to an account of which you login on said mobile device. If someone logs into an account and uploads a certificate then it would be saved to their account data so they don't have to keep re-uploading.

My server requires client certificates to authenticate so it would be great if this feature was added in soon.

**Comment by astorije** [comment] 2017-01-03 05:06
I believe this is a duplicate of https://github.com/thelounge/lounge/issues/430.
To be honest though, we have so much on our plate right now, there is no way this ends up being a priority before a long while, unless someone wants to take a stab at it.

**Closed by astorije** 2017-01-03 05:06 UTC
