### ISSUE TITLE
Settings getting lost on browser restart

### ISSUE THREAD

**Issue by Slind14** [thelounge/lounge#435] opened 2016-06-28 01:15 UTC
Hey,
is there a way to save the user settings e.g. `show joins/leaves`.

**Comment by maxpoulin64** [comment] 2016-06-28 01:18
Settings shouldn't be lost on browser restart. They are stored in a local database, so they should persist unless you browse in private mode or clear your data. I've been using lounge on multiple browsers for a year now and never lost any settings.

What browser are you using? What OS? Do you use any kind of cleaners or privacy enhancing extensions that might interfere with that?

**Comment by Slind14** [comment] 2016-06-28 01:19
I use chrome and vivaldi, both on the latest stable version. Plugins which affect locale storage, cookies and a like is only uBlock origin.

**Comment by Slind14** [comment] 2016-06-28 01:20
Disclaimer: I'm using the docker version, installed 2 days ago, so should be up to date.

**Comment by maxpoulin64** [comment] 2016-06-28 01:21
Interesting, could you check the developer console and see if there's any error there? You mention Docker, so I assume it's running 1.5.0. Would you mind installing the latest master and see if you still reproduce there?

**Comment by Slind14** [comment] 2016-06-28 01:24
Where do I find the dev console? Is it the one that is printed to docker if run in attached mode? If so, its clean.

**Comment by maxpoulin64** [comment] 2016-06-28 01:27
On the browser. The hotkey should be F12 or Ctrl+Shift+I, or can also with right click -> inspect. This will open the developer tools, just go to the console tab from there and change some settings on The Lounge. If there's a problem saving the data, it should print an error there. You can also check from the Resources->Local Storage tab, you should be able to see the settings in JSON format in one of the entries.

**Comment by Slind14** [comment] 2016-06-28 01:32
hmm, I just attempted to the update to 2.0.0-pre.3. Now on this version and the old 1.5.0 I'm getting:

```
lounge    | [SyntaxError: Unexpected token ]]
lounge    | [SyntaxError: Unexpected token ]]
 [...]
```

And I can no longer login:
![image](https://cloud.githubusercontent.com/assets/3914677/16401019/e9bb7a44-3ce0-11e6-99e9-355ee66d4b71.png)


The dev console is clean.

**Comment by Slind14** [comment] 2016-06-28 01:40
Just installed the next version locally on windows 10, clean config (changed public to false) and new user. I do not get the syntaxError but the settings are lost on browser restart, too. The dev console is clean.

**Comment by maxpoulin64** [comment] 2016-06-28 01:48
Something's really weird, and I'm not sure exactly what could cause that. I would expect a crash if there was a problem with local storage. I'm fairly sure this isn't a problem on our side however, as it works fine in most modern browsers (including Edge). The only reason I could think of is that your browser is configured to not store cookies/storage (it's one of the three options in Chrome). StackOverflow seems to suggest that in some cases, blocking third party cookies can also wrongly block the website's cookies as well.

If you go to Chrome's settings, `Show advanced settings...`, in the Privacy section, `Content settings...`  it's the first section: 
![capture d ecran_2016-06-27_21-47-05](https://cloud.githubusercontent.com/assets/5481612/16401218/cf0bde3a-3cb0-11e6-9c3a-3f2e86a7a87a.png)

You can also check that settings are indeed saved:
![capture d ecran_2016-06-27_21-47-28](https://cloud.githubusercontent.com/assets/5481612/16401220/d765ad18-3cb0-11e6-9639-1822f6a53b6c.png)

**Comment by Slind14** [comment] 2016-06-28 01:51
I figured out the syntax issue. It has issues with a tailing `,` e.g. 

https://gist.github.com/Slind14/b211dff8e062c7c722cf9b723f0c6959#file-gistfile1-txt-L17

**Comment by Slind14** [comment] 2016-06-28 01:54
I sent you an email with login data, if you don't mind taking a look your self. This way we can either confirm or iron out if the client environment is at fault.

**Comment by Slind14** [comment] 2016-06-28 01:59
![image](https://cloud.githubusercontent.com/assets/3914677/16401415/95754736-3ce4-11e6-8b35-d1be7501b918.png)
![image](https://cloud.githubusercontent.com/assets/3914677/16401424/ad80a3b6-3ce4-11e6-8baf-7d94188acbff.png)

**Comment by Slind14** [comment] 2016-06-28 02:04
I went ahead and delete the local storage and io, unfortunately this didn't solve the issue either.

**Comment by maxpoulin64** [comment] 2016-06-28 02:04
I confirm it works fine on my side with your server infos:

![capture d ecran_2016-06-27_21-58-40](https://cloud.githubusercontent.com/assets/5481612/16401440/83fa4d62-3cb2-11e6-90e4-c73442202f6d.png)

I even completely closed the browser and made sure it had no remaining background processes, and relaunched it. It remembered by session and everything as expected, all my settings were still there.

I'm puzzled. I have no idea what could be the issue here. But it has to be something with your browser and some kind of local policy. The only other things I can think of trying so far is to try with a blank Chrome profile to make sure it's got all the default settings. Checking with another browser like Firefox should be able to confirm it's your Chrome settings that's the issue. If it doesn't, then it will become really interesting...

**Comment by Slind14** [comment] 2016-06-28 02:10
Hmm, I tested a clean install of firefox, worked fine :)
I reinstalled vivaldi, didn't work, thats odd.
Its being updated in locale storage the second I click it, on chrome and vivaldi

**Comment by MaxLeiter** [comment] 2016-06-28 02:11
Chrome and Vivaldi are both based on Chromium, so it makes sense the issue would persist in both

**Comment by Slind14** [comment] 2016-06-28 02:24
Found a work around. Apparently refreshing the page once before closing chrome/vivaldi lets it restore with the settings on next launch.
My only guess is that the data isn't actually saved to disk when closing the browser. Hence it requiring some sort of event which is being executed on refresh.

Thanks for you quick respond and help :)

One final question, since updating to 2.x the commands config section doesn't seem to work anymore, at least the nickserv identify isn't executed. Was there a syntax change?

**Comment by maxpoulin64** [comment] 2016-06-28 02:36
Well, great then! Looks like it might be a Chrome bug, possibly specific to that particular version. It should save, but I guess nobody noticed because lots of people use browsers for a very long time before closing it...

As for the commands, it looks like it [ends up passing them through `client.input`](https://github.com/thelounge/lounge/blob/master/src/plugins/irc-events/connection.js#L25-L28), so you will have to type commands exactly as if they were sent in chat (so, `/ns identify XXXX`). Might have been broken by changes to the command handling...

**Comment by Slind14** [comment] 2016-06-28 02:39
```
  {
   "name": "EsperNet",
   "host": "eu.irc.esper.net",
   "port": 6697,
   "tls": true,
   "username": "Slind",
   "realname": "Slind",
   "commands": [
    "/msg NickServ identify **"
   ],
   "nick": "Slind",
   "join": ""
  },
```
This is how I have it configured and how it worked with 1.5.0, do you sense anything wrong?

**Comment by maxpoulin64** [comment] 2016-06-28 02:44
I just tried it on master:

```
{
    "nick": "lounge-pr-test",
    "name": "Freenode",
    "host": "chat.freenode.net",
    "port": 6697,
    "tls": true,
    "username": "lounge-user",
    "realname": "The Lounge User",
    "commands": [
        "/msg Max-P test"
    ],
    "join": "#theloungelounge"
}
```

And I did get the PM as expected. So I can only assume it works. Maybe the command failed for some reason?

**Comment by Slind14** [comment] 2016-06-28 02:45
hmm, did the execution order change, maybe its too early, but I don't know how to check

**Comment by maxpoulin64** [comment] 2016-06-28 02:49
It runs the commands right after being registered to the network, just before joining channels. I would suggest running another client to the server and test it as I did by messaging yourself. Then the next debug step would likely be to try copy pasting those commands manually and see what kind of response the server gives you. If there were any errors they should be in the server window.

**Comment by Slind14** [comment] 2016-06-28 03:23
alright thanks

**Comment by Slind14** [comment] 2016-06-28 05:54
In 2.x the connection to the channel is established before the commands are being run, this causes the user to be kicked out of channels which require a registered account. In 1.5 its being executed before the channel join.

**Comment by maxpoulin64** [comment] 2016-06-29 00:28
Are you sure of that? [Commands and channel joins are spaced out 1 second apart each](https://github.com/thelounge/lounge/blob/master/src/plugins/irc-events/connection.js#L20-L39), maybe there needs to be more delay between the two? In the meantime you probably can add empty commands (`""`) to add more delay (they will be ignored).

**Comment by Slind14** [comment] 2016-06-29 09:39
No, I mean its the other way around. Due to being executed too late its closing all those channels which require a signed in user.

**Closed** 2016-09-17 16:24 UTC
Labels: bug, invalid, won't fix
