### ISSUE TITLE
Allow tabbing out of the input field

### ISSUE THREAD

**Issue by dgw** [thelounge/lounge#433] opened 2016-06-25 18:29 UTC
Follow-up to #428

**Comment by xPaw** [comment] 2016-06-25 18:32
Possibly to be handled in #379

**Comment by astorije** [comment] 2017-02-18 07:44
I'm afraid #379 did not fix this.

**Comment by astorije** [comment] 2017-08-17 06:07
Duplicate of https://github.com/thelounge/lounge/issues/935 (which has more details).

**Closed by astorije** 2017-08-17 06:07 UTC
Labels: enhancement
