### ISSUE TITLE
Can't go private... :'(

### ISSUE THREAD

**Issue by zkanda** [thelounge/lounge#655] opened 2016-09-29 10:03 UTC
Hi, I'm trying to run `lounge` in private mode but this is what I'm getting. 

``` bash
➜  ~ lounge --version
2.0.1
➜  ~ lounge start --private
2016-09-29 10:01:35 [INFO] The Lounge v2.0.1 is now running on http://*:9000/ in public mode
2016-09-29 10:01:35 [INFO] Press ctrl-c to stop
```

**Comment by xPaw** [comment] 2016-09-29 10:36
Change the private variable in the config.

**Comment by astorije** [comment] 2016-09-29 14:25
Looks like [our documentation](https://thelounge.github.io/docs/getting_started/usage.html#start) is severely outdated :(

**Comment by xPaw** [comment] 2016-09-30 20:58
Okay the trick is to do `lounge start -- --public`, I'm not sure why the extra `--` is required to get any params working.

**Comment by astorije** [comment] 2016-09-30 22:42
Yeah, that's a npm thing. But `lounge start --private` should still start
as expected :/

**Comment by daftaupe** [comment] 2016-10-13 08:11
Hello, actually it's the same for the port option, it's not taken into account either. I guess it's a general issue with how thelounge process arguments.
@xPaw trick works perfectly, but maybe opening a new issue for argument parsing would make more sense.

**Comment by astorije** [comment] 2016-12-15 06:24
Duplicate of https://github.com/thelounge/lounge/issues/517.

**Closed by astorije** 2016-12-15 06:24 UTC
