### ISSUE TITLE
"Use /connect to reconnect" doesn't

### ISSUE THREAD

**Issue by dgw** [thelounge/lounge#917] opened 2017-02-12 08:43 UTC
In v2.2.0, using `/connect` shows "Connected to the network", but about two minutes later gets disconnected again. No channels are joined.

Note: I am connecting to a ZNC, not directly to a network.

**Comment by dgw** [comment] 2017-02-12 08:43
Ugh, new Android app for github, wrong button.

**Comment by Cldfire** [comment] 2017-02-12 15:24
I actually just started experiencing this issue on 2.2.0 myself. I had no problems connecting to ZNC with any prior version.

**Comment by dgw** [comment] 2017-02-12 15:35
Yep. This worked in 2.1.0, before I updated my instance to 2.2.0. Seems to be a regression.

**Comment by rib** [comment] 2017-02-14 13:41
When I loose my connection to my znc proxy I see `Disconnected from the network, and will not reconnect. Use /connect to reconnect again.` but using `/connect` doesn't seem to do anything for me (no log output from lounge running in the foreground of a terminal on localhost or in the server tab in the UI).

I'm not aware of automatic reconnection ever working for me (even since #18) so I'm not sure this is the same more-recent regression others are describing.

**Comment by dgw** [comment] 2017-02-15 03:09
@rib I've never seen auto-reconnection work either, on my instance. It sounds like what you're experiencing is the same issue (same error message, same symptom), but perhaps it's not a regression—just a bug with ZNC specifically?

**Comment by drkitty** [comment] 2017-02-17 04:58
I'm having this issue too. I'm running git tag `v2.2.0` in dev mode with nginx as a reverse proxy. I turned on the `debug.ircFramework` setting and forced a disconnect by null routing the server. Then I restored the route and ran `/connect`, and it failed to reconnect. [Here's the TL server output and what I saw in the web app.](https://gist.github.com/drkitty/319b2851658ba53c3967da4ed7356e96)

**Comment by astorije** [comment] 2017-02-17 05:00
Thanks @drkitty!

@xPaw, is that any useful to you?

**Comment by xPaw** [comment] 2017-02-17 05:26
Looks like ping timeout is the initial trigger for the issue.

**Comment by xPaw** [comment] 2017-02-17 05:29
https://github.com/kiwiirc/irc-framework/issues/56

**Comment by drkitty** [comment] 2017-02-17 05:30
@xPaw Shouldn't you still be able to manually reconnect, though? Because that's what I was testing here. Or are auto and manual reconnect related somehow?

**Comment by xPaw** [comment] 2017-02-17 05:31
I'm thinking the quit is throwing it into some invalid state. cc @prawnsalad

**Comment by xPaw** [comment] 2017-02-22 19:26
Confirmed the bug, there's definitely some weirdness that doesn't do anything after issuing /connect.

**Comment by astorije** [comment] 2017-02-23 00:22
@xPaw, do you think that would come from us or `irc-framework`?

**Comment by xPaw** [comment] 2017-02-23 04:49
I haven't dug into the code, but I expect it to be in the framework.

**Comment by xPaw** [comment] 2017-03-18 16:06
This should have been fixed in 2.2.2

**Closed** 2017-04-23 15:53 UTC
Labels: bug
