### ISSUE TITLE
blank page after system suspend

### ISSUE THREAD

**Issue by niv** [thelounge/lounge#623] opened 2016-09-20 10:21 UTC
Hey,

lounge is great so far!  Though I found a small, but annoying niggle, when running 2.0.0-rc1:

With thelounge open, after returning my system from sleep, the page is blank and does not auto-refresh/reconnect. I think the same behaviour can be observed when killing the serverside process. I've seen it happen in Chrome and Electron (nativefier).

I'm not sure how it gets to the blank page; but I think, what it should do instead is attempt reconnection attempts forever?

**Comment by astorije** [comment] 2016-09-21 04:23
Are you running this on your laptop?
FYI, The Lounge is meant to be run on a machine that stays up, but agreed that it should be trying to reconnect at the very least.

**Comment by astorije** [comment] 2016-09-21 04:24
This seems to me like a duplicate of https://github.com/thelounge/lounge/issues/595. Closing as such.

**Closed** 2016-09-21 04:24 UTC
Labels: bug, duplicate

**Comment by niv** [comment] 2016-09-21 10:00
@astorije  Thanks for checking!  However, this isn't a dupe.

The serverside parts run on a dedicated VM. I'm talking about the js frontend that just replaces itself with a blank page after coming out of suspend on my laptop. What I would expect instead is that it reconnects transparently, like any desktop client would.
