### ISSUE TITLE
Per-channel join/part/nick hiding options

### ISSUE THREAD

**Issue by nornagon** [thelounge/lounge#602] opened 2016-09-12 22:51 UTC
In some busy channels I want to hide joins/parts/nicks, but in other smaller channels I'd like to see when people enter and leave. I couldn't find a way to set these options on a per-channel basis, but maybe I just missed something :)

**Comment by xPaw** [comment] 2016-09-17 16:25
Duplicate of #85

**Closed by xPaw** 2016-09-17 16:25 UTC
