### ISSUE TITLE
Tab auto-complete name fetches from PMs

### ISSUE THREAD

**Issue by MaxLeiter** [thelounge/lounge#64] opened 2016-02-18 08:12 UTC
Using tab to auto-complete a name doesn't just complete names from users in the channel, but it also completes names from users you have a private conversation open with. Investigating now

**Comment by YaManicKill** [comment] 2016-02-18 08:40
That explains so much actually.

**Comment by MaxLeiter** [comment] 2016-02-18 08:44
I believe the issue is originating from here: https://github.com/thelounge/lounge/blob/master/client/js/lounge.js#L831-L863

How? I'm not too sure, it doesn't make much sense. PM's don't have the `active` class applied (unless when active, like they're supposed to), they aren't children of a `users` class, and they aren't part of the `commands` array. I'm not sure why this is happening...

**Comment by maxpoulin64** [comment] 2016-02-22 05:12
This is actually not a bug, it is done on purpose: https://github.com/thelounge/lounge/blob/master/client/js/lounge.js#L851

That selector loops over all channel buttons in the sidebar to extrac the channel names and tab complete them, which has the side effect of also including PMs. Since it checks for something that is *not* a lobby, it seems PMs are supposed to be tab-completed after all.

If this is still considered a bug, it should be as easy as changing changing `sidebar.find(".chan")` to `sidebar.find(".chan.channel")` and get rid of the if altogether.

**Comment by astorije** [comment] 2016-02-22 05:15
If I understood correctly, this auto-completes user nicks outside of the current channel. If so, then it looks like a bug indeed (even if hidden behind a this-is-not-a-bug-it's-a-feature :p). Completion should only match users of the current channel, or the sole recipient in PMs.

**Comment by maxpoulin64** [comment] 2016-02-22 05:23
That is only if we declare that tab should only autocomplete nicks, nicks in the current channel in particular. Currently, it tries to autocomplete everything it can: [commands](https://github.com/thelounge/lounge/blob/master/client/js/lounge.js#L834), [nicks](https://github.com/thelounge/lounge/blob/master/client/js/lounge.js#L847) and [channels/PMs](https://github.com/thelounge/lounge/blob/master/client/js/lounge.js#L851). We would need to ask @erming to know for sure, but from the look of the code it definitely looks like it's done on purpose to autocomplete other people's nicks in PMs.

Honestly I think this is a cool feature even if it does look like a bug, and I'm pretty sure I used it by accident during a bunch of channel conflicts like "I was talking to XXXXX about in private about his ban and I think we should unban her". And it does no harm, it's just slightly more useful.

**Comment by astorije** [comment] 2016-02-22 05:27
I do think this is very clumsy and I wouldn't be surprised if everyone who used that feature used it by accident. Heck, I didn't even know you could auto-complete with open channels :-) But not network names... Very clumsy indeed.

**Comment by dgw** [comment] 2017-02-25 12:33
Bitten by this yesterday, hit Tab to check if a nick was present in channel and it completed even though the nick was not in channel…because I had a PM window open with that user.

**Comment by xPaw** [comment] 2017-04-26 08:40
I think this is now fixed.

**Comment by YaManicKill** [comment] 2017-04-26 08:55
Just tested on master, I am not able to reproduce it anymore. Woop.

**Closed by YaManicKill** 2017-04-26 08:55 UTC
Labels: bug
