### ISSUE TITLE
Differentiate days in chat logs

### ISSUE THREAD

**Issue by MaxLeiter** [thelounge/lounge#132] opened 2016-03-02 03:58 UTC
Currently there's no way to tell when one day starts and when another begins. I'd personally prefer an \<hr\> (or CSS equivalent) with the date (or days ago) in faded letters above it.

Example:

1 day ago
<hr>
Message: hey

**Comment by YaManicKill** [comment] 2016-03-02 08:30
Duplicate of #89

**Closed** 2016-03-02 08:30 UTC
Labels: duplicate
