### ISSUE TITLE
Auto-complete commands - one "press enter" too much

### ISSUE THREAD

**Issue by christer88** [thelounge/lounge#1221] opened 2017-06-12 14:09 UTC
Is it possible to remove the extra press-enter when I type a command that have the auto-complete list above? E.g. I type "/reconnect", press enter and press enter again to post it. This is one enter too much.

This doesn't seem to be the case for smileys.

**Comment by xPaw** [comment] 2017-06-12 14:09
Duplicate of #1182.

**Closed by xPaw** 2017-06-12 14:09 UTC
