### ISSUE TITLE
Run network commands on reconnect.

### ISSUE THREAD

**Issue by Zegnat** [thelounge/lounge#772] opened 2016-11-30 12:20 UTC
After a disconnect, I followed the on-screen directions and used `/reconnect`.

For this network, my settings include a set of `commands` as per [the user configuration documentation](https://thelounge.github.io/docs/server/users.html) to identify my account. I assumed these would be send on reconnect, but it looks like they are not. This meant I lost my username for a while.

Is something wrong on my end, or does lounge not replay `commands` on reconnect?

**Comment by Raqbit** [comment] 2016-11-30 13:35
If the authentication you're talking about is nickserv, you can auto identify by putting it in the passwords field (of the server). It's still an issue that the commands do not get run on reconnect though.

**Comment by Zegnat** [comment] 2016-11-30 14:35
> If the authentication you're talking about is nickserv, you can auto identify by putting your nickserv password in the passwords field (of the server).

Neat. Is this documented anywhere? I thought this would be the actual server password, not automagically identify me with NickServ. The configuration also shows NickServ as an example use of the `commands` property.

**Comment by Raqbit** [comment] 2016-11-30 14:58
It /is/ the actual server password field. It's just that most nickserv
running public servers will use it to automatically log you in. It's a
temporary solution for this issue.

**Comment by xPaw** [comment] 2016-12-02 16:23
The commands are executed after every successful connection, there is no separate logic for initial and the following connections. I'm thinking the command is executed but the server doesnt do anything with it as it might be too early.

**Comment by Zegnat** [comment] 2016-12-02 16:28
> I'm thinking the command is executed but the server doesnt do anything with it as it might be too early.

If that’s the case, wouldn’t it always “be too early”? I seem to recall it authenticated me with NickServ correctly on the first connect.

**Comment by xPaw** [comment] 2016-12-02 16:29
The logic is always the same: run commands after registration. There is no special logic for "first connection".

**Comment by MaxLeiter** [comment] 2016-12-02 17:01
Could be fixed by kiwiirc/irc-framework#66?

**Comment by xPaw** [comment] 2016-12-02 17:02
Unlikely.

**Comment by xPaw** [comment] 2016-12-17 08:26
Can you give this a try on master and see if the issue is resolved?

**Comment by Zegnat** [comment] 2016-12-19 07:46
> Can you give this a try on master and see if the issue is resolved?

How would I try this, other than waiting for my connection with the IRC server to be dropped again?

**Comment by PolarizedIons** [comment] 2016-12-19 09:17
@Zegnat you could run master on your local machine, and then disconnect from your network (i.e. pull out your ethernet cable, or disconnect from wifi), and then reconnect

**Comment by astorije** [comment] 2017-04-14 05:34
No activity on this for a while, and as far as I know this should work. Closing for now, let us know if you're experiencing issues again.

**Closed by astorije** 2017-04-14 05:34 UTC
