### ISSUE TITLE
Lounge crashes when failing a DNS lookup

### ISSUE THREAD

**Issue by omnicons** [thelounge/lounge#352] opened 2016-05-27 00:02 UTC
The logs from the crash and the stack trace below:

```
2016-05-26 22:35:12 [DEBUG] IRC socket error { Error: getaddrinfo ENOTFOUND irc.canternet.net irc.canternet.net:6009
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:79:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'irc.canternet.net',
  host: 'irc.canternet.net',
  port: 6009 }
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 54.244.255.81:6009
    at Object.exports._errnoException (util.js:949:11)
    at exports._exceptionWithHostPort (util.js:972:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)

npm ERR! Linux 4.2.5-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.1.0
npm ERR! npm  v3.9.0
npm ERR! code ELIFECYCLE
npm ERR! thelounge@2.0.0-pre.1 start: `node index`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the thelounge@2.0.0-pre.1 start script 'node index'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the thelounge package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs thelounge
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls thelounge
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dusk/lounge/npm-debug.log

NPM-DEBUG.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@3.9.0
3 info using node@v6.1.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle thelounge@2.0.0-pre.1~prestart: thelounge@2.0.0-pre.1
6 silly lifecycle thelounge@2.0.0-pre.1~prestart: no script for prestart, continuing
7 info lifecycle thelounge@2.0.0-pre.1~start: thelounge@2.0.0-pre.1
8 verbose lifecycle thelounge@2.0.0-pre.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle thelounge@2.0.0-pre.1~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/dusk/lounge/node_modules/.bin:/usr/bin:/usr/local/sbin:/u$
10 verbose lifecycle thelounge@2.0.0-pre.1~start: CWD: /home/dusk/lounge
11 silly lifecycle thelounge@2.0.0-pre.1~start: Args: [ '-c', 'node index' ]
12 silly lifecycle thelounge@2.0.0-pre.1~start: Returned: code: 1  signal: null
13 info lifecycle thelounge@2.0.0-pre.1~start: Failed to exec start script
14 verbose stack Error: thelounge@2.0.0-pre.1 start: `node index`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid thelounge@2.0.0-pre.1
16 verbose cwd /home/dusk/lounge
17 error Linux 4.2.5-1-ARCH
18 error argv "/usr/bin/node" "/usr/bin/npm" "start"
19 error node v6.1.0
20 error npm  v3.9.0
21 error code ELIFECYCLE
22 error thelounge@2.0.0-pre.1 start: `node index`
22 error Exit status 1
23 error Failed at the thelounge@2.0.0-pre.1 start script 'node index'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the thelounge package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node index
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs thelounge
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls thelounge
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by xPaw** [comment] 2016-05-28 10:51
I just tried this, I can see the `[DEBUG] IRC socket error` (which is expected), but it did not crash, and the client is still running fine.

The crash in your seems unrelated, and due to `Error: connect ETIMEDOUT 54.244.255.81`

**Comment by maxpoulin64** [comment] 2016-05-28 21:14
@omnicons: in light of the other issue we debugged yesterday with you being on 1.3 instead of 2.0 as you thought (wrong executable), I'm guessing this is probably solved.

**Comment by omnicons** [comment] 2016-05-28 21:16
No no, I was only on 1.3 yesterday after I restarted it in tmux instead.

**Comment by maxpoulin64** [comment] 2016-05-28 21:17
Yeah I deleted my comment right after posting it, realizing it had obvious 2.0.0 traits. My bad, sorry for the false alarm :)

**Comment by omnicons** [comment] 2016-06-01 11:35
Outside of the two times that it crashed before, upon the second which I submitted the report, I'm unable to reproduce the issue on my machine on the latest `master` so I'll chalk it up to my own error anyway as neither of us can reproduce it anymore. Sorry about that and thanks for looking into it!

**Comment by omnicons** [comment] 2016-06-01 11:50
RE: Deleted comment; I was mistaken, as I submitted the comment Lounge crashed. It took it a good minute or so for it to die once I made it try to connect, to be clear this is a fresh install of 'master' having run 'npm install' and everything else seems to be relatively normal.

```
2016-06-01 11:32:09 [DEBUG] IRC socket error { Error: getaddrinfo ENOTFOUND irc.canternet.net irc.canternet.net:6697
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:79:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'irc.canternet.net',
  host: 'irc.canternet.net',
  port: 6697 }
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 54.228.211.168:6009
    at Object.exports._errnoException (util.js:953:11)
    at exports._exceptionWithHostPort (util.js:976:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)

npm ERR! Linux 4.2.5-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.2.0
npm ERR! npm  v3.9.2
npm ERR! code ELIFECYCLE
npm ERR! thelounge@2.0.0-pre.1 start: `node index`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the thelounge@2.0.0-pre.1 start script 'node index'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the thelounge package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs thelounge
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls thelounge
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dusk/lounge/npm-debug.log

-------------

NPM-DEBUG.LOG

-------------

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@3.9.2
3 info using node@v6.2.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle thelounge@2.0.0-pre.1~prestart: thelounge@2.0.0-pre.1
6 silly lifecycle thelounge@2.0.0-pre.1~prestart: no script for prestart, continuing
7 info lifecycle thelounge@2.0.0-pre.1~start: thelounge@2.0.0-pre.1
8 verbose lifecycle thelounge@2.0.0-pre.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle thelounge@2.0.0-pre.1~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/dusk/lounge/node_modules/.bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
10 verbose lifecycle thelounge@2.0.0-pre.1~start: CWD: /home/dusk/lounge
11 silly lifecycle thelounge@2.0.0-pre.1~start: Args: [ '-c', 'node index' ]
12 silly lifecycle thelounge@2.0.0-pre.1~start: Returned: code: 1  signal: null
13 info lifecycle thelounge@2.0.0-pre.1~start: Failed to exec start script
14 verbose stack Error: thelounge@2.0.0-pre.1 start: `node index`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid thelounge@2.0.0-pre.1
16 verbose cwd /home/dusk/lounge
17 error Linux 4.2.5-1-ARCH
```

**Comment by morgzz** [comment] 2016-06-01 12:12
I think you maybe using the wrong connection settings... possibly irc.canternet.org not .net?

**Comment by morgzz** [comment] 2016-06-01 12:35
Actually what I previously mentioned wouldn't make sense.
I'm now guessing you had the correct settings as 54.244.255.81 maintained by canternet.org

54.244.255.81 is from United States (US) in region North America
Input: 54.244.255.81
canonical name: chrysalis.canternet.org
Registered Domain: canternet.org

I'm guessing something possibly on their end is miss routing you to irc.canternet.net.

In your Stack Trace, see the **bold** below.
```
016-06-01 11:32:09 [DEBUG] IRC socket error { Error: getaddrinfo ENOTFOUND irc.canternet.net irc.canternet.net:6697
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:79:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: '**irc.canternet.net**',
  host: '**irc.canternet.net**',
  port: 6697 }
events.js:160
```

Admittedly I'm completely new to this project. I'm guessing this could have something to do with why it's crashing. Possibly a misconfigured load balancer on canternet's side.

**Comment by omnicons** [comment] 2016-06-01 15:41
Oh I know, but the application should not crash upon a failed connection.
That interrupts service for everyone.

**Comment by maxpoulin64** [comment] 2016-06-05 00:57
I can't seem to reproduce either. I reproduced both stack traces, without a crash.

```
2016-06-05 00:33:10 [DEBUG] IRC socket error { Error: getaddrinfo ENOTFOUND irc.max-p.me irc.max-p.me:6667
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:79:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'irc.max-p.me',
  host: 'irc.max-p.me',
  port: 6667 }
2016-06-05 00:38:55 [DEBUG] IRC socket error { Error: connect ETIMEDOUT 167.114.206.88:6667
    at Object.exports._errnoException (util.js:953:11)
    at exports._exceptionWithHostPort (util.js:976:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '167.114.206.88',
  port: 6667 }
```

Using npm 3.9.3 and node 6.2.0, fresh master install. Seems like an error is not caught somewhere where it should, but the stack trace doesn't point to any of our code at all. I would like to blame node itself for that, but considering I also run Arch and thus in theory the same packages, I should get the error too. But I don't.

I did manage to get this crash:
```
2016-06-05 00:56:11 [DEBUG] IRC socket error Error: write after end
    at writeAfterEnd (_stream_writable.js:166:12)
    at Socket.Writable.write (_stream_writable.js:217:5)
    at Socket.write (net.js:650:40)
    at Connection._write (/mnt/storage/max-p/Sync/remote/Projects/lounge/node_modules/irc-framework/src/connection.js:180:24)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Connection.Writable.write (_stream_writable.js:220:11)
    at IrcCommandHandler.handlers.PING (/mnt/storage/max-p/Sync/remote/Projects/lounge/node_modules/irc-framework/src/commands/handlers/misc.js:79:25)
    at IrcCommandHandler.dispatch (/mnt/storage/max-p/Sync/remote/Projects/lounge/node_modules/irc-framework/src/commands/handler.js:49:37)
    at IrcCommandHandler._write (/mnt/storage/max-p/Sync/remote/Projects/lounge/node_modules/irc-framework/src/commands/handler.js:35:10)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:166:12)
    at Socket.Writable.write (_stream_writable.js:217:5)
    at Socket.write (net.js:650:40)
    at Connection._write (/mnt/storage/max-p/Sync/remote/Projects/lounge/node_modules/irc-framework/src/connection.js:180:24)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Connection.Writable.write (_stream_writable.js:220:11)
    at IrcCommandHandler.handlers.PING (/mnt/storage/max-p/Sync/remote/Projects/lounge/node_modules/irc-framework/src/commands/handlers/misc.js:79:25)
    at IrcCommandHandler.dispatch (/mnt/storage/max-p/Sync/remote/Projects/lounge/node_modules/irc-framework/src/commands/handler.js:49:37)
    at IrcCommandHandler._write (/mnt/storage/max-p/Sync/remote/Projects/lounge/node_modules/irc-framework/src/commands/handler.js:35:10)
```

But it's the one @MaxLeiter is having, and unrelated to this issue.

**Comment by YaManicKill** [comment] 2016-07-04 07:20
So, if we can't reproduce, shall we just throw some catcher around where it is being thrown and just leave it like that? It's obviously not ideal, but it'll be something, at least...

**Comment by xPaw** [comment] 2016-07-04 07:38
@YaManicKill, vectr0n hit this issue yesterday while debugging.

**Comment by xPaw** [comment] 2016-07-04 11:28
@YaManicKill somewhat.

**Comment by xPaw** [comment] 2016-07-04 15:11
Found the problem and fixed it: https://github.com/kiwiirc/irc-framework/pull/61

**Comment by astorije** [comment] 2016-08-20 03:43
This issue will be resolved only when https://github.com/kiwiirc/irc-framework/pull/61 gets merged, makes it into a release and we pull that new version in our `package.json`.

**Comment by astorije** [comment] 2016-09-15 05:56
I am removing 2.0.0 milestone for now. If by any luck it gets released before we ship it, then we'll add it back, otherwise it will be for later. I am really willing to ship 2.0.0 in a matter of days now.

**Closed** 2016-12-12 12:13 UTC
Labels: bug

**Comment by TuSuNaMi** [comment] 2017-05-12 13:11
Hello

Version 2.2 give simillar error,

`dns.js:239
    if (err) throw errnoException(err, bindingName);
             ^

Error: getHostByAddr EINVAL
    at Object.exports._errnoException (util.js:1018:11)
    at errnoException (dns.js:33:15)
    at Object.query [as reverse] (dns.js:239:20)
    at reverseDnsLookup (/usr/lib/node_modules/thelounge/src/server.js:258:6)
    at Socket.auth (/usr/lib/node_modules/thelounge/src/server.js:329:4)
    at Namespace.<anonymous> (/usr/lib/node_modules/thelounge/src/server.js:78:9)
    at emitOne (events.js:96:13)
    at Namespace.emit (events.js:188:7)
    at Namespace.emit (/usr/lib/node_modules/thelounge/node_modules/socket.io/lib/namespace.js:209:10)
    at /usr/lib/node_modules/thelounge/node_modules/socket.io/lib/namespace.js:176:14
`
