### ISSUE TITLE
Sort channels in a network

### ISSUE THREAD

**Issue by realies** [thelounge/lounge#1741] opened 2017-11-24 07:20 UTC
```
04:25 <realies> to be able to reorder channels in a network alphabetically (maybe via a context menu option); yay or nay?
04:33 <kode54>  that would be handy
04:33 <kode54>  and I'd like to see it as (right click) "Sort"
```

**Comment by astorije** [comment] 2017-11-24 08:50
Closing as duplicate of #53

**Closed by astorije** 2017-11-24 08:50 UTC
