### ISSUE TITLE
[Feature] Show Travis build message in one block

### ISSUE THREAD

**Issue by thenets** [thelounge/lounge#1664] opened 2017-10-26 10:46 UTC
Problem:
When Travis create a new build a message is sent to IRC but in 3 parts.
![image](https://user-images.githubusercontent.com/2138276/32048959-02da164e-ba2a-11e7-9d49-4f2683d536a6.png)

Suggestion:
Merge the 3 lines into only one and show the badge for build success/error.

**Comment by xPaw** [comment] 2017-10-26 10:48
Duplicate of #659

**Closed by xPaw** 2017-10-26 10:48 UTC

**Comment by thenets** [comment] 2017-10-26 11:18
It's not exactly duplicated.
Badge status will be awesome too.

**Comment by xPaw** [comment] 2017-10-26 11:19
This is way too specific for one service, so that's not going to happen.

**Comment by thenets** [comment] 2017-10-26 11:22
Ah, ok.
CI services are too important and there's not much available but ok. Maybe I can help to implement it later.

**Comment by MiniDigger** [comment] 2017-10-26 13:42
The point is that hard coding such a feature for just one service is kinda pointless. Then ppl want like every service added. The better solutions is to take a more general approach and allow teams to do that merging so that you can easily define it for many services. That's exactly what the linked issue would allow you to do. That's why this is a duplicate.
