### ISSUE TITLE
Feature request: Restore channel history, when leaving and rejoining a channel.

### ISSUE THREAD

**Issue by Varbaek** [thelounge/lounge#1259] opened 2017-06-23 16:20 UTC
I tried searching for this, to see if it was already requested.

Basically, when I've been active in a channel, and leave it, and subsequently rejoin it, then I can't view the channel history in the browser? 

I suspect it's currently only possible to view the channel history, by looking at the logs manually at this point in time?

**Comment by PolarizedIons** [comment] 2017-06-23 16:25
related to issue #442 

And yes, @Varbaek, lounge does not currently support loading messages from logs :\

**Comment by astorije** [comment] 2017-06-27 04:13
Yup, duplicate of #442, and some beginning of work on this in #506 and #663. Stay tuned!

**Closed by astorije** 2017-06-27 04:13 UTC
