### ISSUE TITLE
Use multi-line input for chat

### ISSUE THREAD

**Issue by dgw** [thelounge/lounge#196] opened 2016-03-15 00:00 UTC
I propose changing the input to a multi-line `textarea` that auto-resizes vertically.

This would serve a couple different purposes:

1. Lets the user see all the text they've input
    * unless it's longer than the input's `max-height`, which for IRC it probably won't be
2. Would likely solve the #137 input history problem, as browsers don't keep `textarea` input history
    * I've never seen this on desktop, but it blocks the chat while typing in Chrome for Android

The most elegant implementation of this I've personally used is in [Textual](https://github.com/Codeux-Software/Textual), which I bring up because its UI is very similar to The Lounge: servers/channels on the left, chat in the middle, users on the right, and a bottom bar that contains action buttons on the left and a text input that fills the rest of it.

Textual's input expands vertically as the text gets longer, but the action buttons stay anchored to the bottom left corner of the bar:

![screenshot 2016-03-14 18 57 14](https://cloud.githubusercontent.com/assets/164140/13763754/0cd7cc2c-ea1f-11e5-862e-776bc6905509.png)

![screenshot 2016-03-14 18 58 41](https://cloud.githubusercontent.com/assets/164140/13763777/2d3da36a-ea1f-11e5-93c9-169b257588f9.png)

Thoughts?

**Comment by MaxLeiter** [comment] 2016-03-15 01:52
@YaManicKill began work on this here: https://github.com/thelounge/lounge/tree/yamanickill/multiple-lines

**Comment by YaManicKill** [comment] 2016-03-15 12:22
Yep, duplicate of #177 

I'll get this finished hopefully this week or weekend. It's just got a few small bugs.

Thanks for your input though, @dgw, I hadn't figured out what to do with the buttons. I think you are probably right that they should anchor to the bottom, so I'll get that done :-)

**Closed by YaManicKill** 2016-03-15 12:22 UTC
Labels: duplicate
