### ISSUE TITLE
URL parser trips on trailing >

### ISSUE THREAD

**Issue by dgw** [thelounge/lounge#264] opened 2016-04-17 18:33 UTC
The `>` character becomes part of the link, and is also followed by a semicolon:

![image](https://cloud.githubusercontent.com/assets/164140/14589156/44df3818-04a9-11e6-942a-b5b07949815d.png)

**Comment by xPaw** [comment] 2016-04-17 18:36
Duplicate of #199.

**Closed by xPaw** 2016-04-17 18:36 UTC

**Comment by dgw** [comment] 2016-04-17 18:40
Whoops. -_-
