### ISSUE TITLE
Sorting the channel list

### ISSUE THREAD

**Issue by wiiaam** [thelounge/lounge#1506] opened 2017-09-06 09:01 UTC
Is there any way to sort the channel/queries list? Currently it's sorted by last joined, would be cool to be able to sort this alphabetically, as it can be a hassle to find a channel when you're in a few.

An ideal sort would be channels at the top, queries at the bottom. Channels sorted ignoring hash symbols, so that double hash ## channels can be sorted beside single hash # channels.

**Comment by YaManicKill** [comment] 2017-09-06 09:38
Currently, it will automatically sort on restart, and you can manually reorganise them, but there is nothing else.

Closing as a duplicate of #53

**Closed by YaManicKill** 2017-09-06 09:38 UTC

**Comment by wiiaam** [comment] 2017-09-06 09:50
Cheers, didn't spot the old issue, will give it a look
