### ISSUE TITLE
Allow renaming network entries in the sidebar

### ISSUE THREAD

**Issue by shinji257** [thelounge/lounge#532] opened 2016-07-28 07:44 UTC
Basically to allow changing the name of the network in the sidebar to something else after you have connected.  As it is right now you have to disconnect from the network then reconnect so you can change the name.  The name may need to be changed either by preference or because you made a typo during connection and didn't notice it until later.  Having to disconnect/reconnect may interrupt workflow and you end up losing logs as it is right now.

**Comment by xPaw** [comment] 2016-08-20 12:27
Duplicate of #179

**Closed by xPaw** 2016-08-20 12:27 UTC
Labels: enhancement
