### ISSUE TITLE
ZNC username issue after receiving WHO reply for self

### ISSUE THREAD

**Issue by kode54** [thelounge/lounge#1827] opened 2017-12-12 00:39 UTC
I've posted the issue here, kiwiirc/irc-framework#131, but I'm listing it here for reference, since it came into effect when that version of irc-framework was adopted.

**Comment by dgw** [comment] 2017-12-12 04:03
Note: irc-framework version update was committed with the merge of #1782.

This sounds like a potential release blocker for 2.7.0 to me.

**Comment by astorije** [comment] 2017-12-12 04:22
> This sounds like a potential release blocker for 2.7.0 to me.

@thelounge/maintainers, do you agree with this? Adding the milestone until then, feel free to remove if not.

Thanks for the bug report @kode54!
In the end, is it something that should be fixed in this repo or `irc-framework` ?

**Comment by dgw** [comment] 2017-12-12 05:12
> In the end, is it something that should be fixed in this repo or `irc-framework`?

Ideally it would be fixed in the library, because it broke behavior that works on any number of other IRC consumers (and used to work in the library too—it's a regression). One of ZNC's maintainers is involved on the irc-fw ticket, so let's see where that goes in the next few days, perhaps.

**Comment by astorije** [comment] 2017-12-12 05:33
Sweet, thanks for keeping an eye on that, @dgw!! 🙏

**Comment by astorije** [comment] 2018-01-02 01:36
FYI, a fix for this (https://github.com/kiwiirc/irc-framework/pull/133) was merged today so it will be fixed when `irc-framework` gets released and bumped here.

**Closed** 2018-01-05 09:32 UTC
Labels: Type: Bug
