### ISSUE TITLE
Handle disconnect

### ISSUE THREAD

**Issue by y-lohse** [thelounge/lounge#220] opened 2016-03-25 12:45 UTC
Hello,
I cheked in on irc yesterday with a bug and wanted to follow through here.

Sometimes, The Lounge loses the connexion to the irc server / internet, but when that happens, nothing is reported to the user. Everything seems normal except you don't receive any more messages and can't send any either.

I'm still a bit confused about when this happens and can't reproduce it reliably, but apparently it's something inherited from shout (see [here](https://github.com/erming/shout/issues/235) and [here](https://github.com/erming/shout/issues/395) for example).

Are there any plans to address this?

**Comment by xPaw** [comment] 2016-03-25 12:48
Duplicate of #18

**Closed by xPaw** 2016-03-25 12:48 UTC

**Comment by y-lohse** [comment] 2016-03-25 12:53
Aw sorry, I searched the issues for "disconnect" so didn't find it^^
