### ISSUE TITLE
Add option to autoreload on timeout or enable socket reconnect

### ISSUE THREAD

**Issue by bews** [thelounge/lounge#1174] opened 2017-05-18 16:30 UTC
Notifications don't get through because of timeouts.

**Comment by astorije** [comment] 2017-05-20 06:38
I believe this is a duplicate of https://github.com/thelounge/lounge/issues/421. Make sure to include enough details to your issue so we are all on the same page.

Regarding the issue itself, that definitely won't be an option and should just work for everyone. However, as mentioned some days ago in the IRC channel, it is sadly not just about enabling socket.io's reconnect mode. I forget why but feel free to take a stab at it if you feel adventurous 😅

**Closed by astorije** 2017-05-20 06:38 UTC
