### ISSUE TITLE
Broken things in recent changes on action display

### ISSUE THREAD

**Issue by astorije** [thelounge/lounge#31] opened 2016-02-14 00:33 UTC
@xPaw's work on actions (https://github.com/erming/shout/pull/588) is a huge improvement, but I noticed some issues/regressions that could be improved. Listing them here as they are all defects around the same subject:

- [x] 1. When joining a channel, the statement to indicate the topic is "#channel has changed the topic to ...". This is only true when the topic is actually changed, when joining the wording should be different.
<img width="669" alt="screen shot 2016-02-13 at 19 21 18" src="https://cloud.githubusercontent.com/assets/113730/13030863/05a643f2-d287-11e5-958d-0f730bb56f57.png">

- [x] 2. When *colored nicknames* are enabled in the settings, nicks in actions are not colored:

  Before | After
--- | ---
<img width="147" alt="screen shot 2016-02-13 at 14 10 02" src="https://cloud.githubusercontent.com/assets/113730/13030878/654257ba-d287-11e5-876d-14d6e890e389.png"> | <img width="306" alt="screen shot 2016-02-13 at 14 09 54" src="https://cloud.githubusercontent.com/assets/113730/13030880/6948c4fc-d287-11e5-91e5-a916fedc0395.png">

- [x] 3. As shown by the previous screenshots, action are now in black. They should be displayed in gray as before to not get as much attention as normal message.

- [x] 4. From the pre-Shout/The Lounge days I can remember, I think I used to see "[nick] has changed the topic..." instead of "[channel] has changed the topic...", i.e. is the nick that changed the topic last saved along with the topic? If so that's what should be displayed instead!

**Comment by xPaw** [comment] 2016-02-14 09:11
1. perphaps can be fixed by changing `changed` to `set`?
2. Colored nicknames are an absolutely mess, and when you use a different theme (e.g. morning), it gets even worse. The whole thing needs fixing, not in just actions.

**Comment by astorije** [comment] 2016-02-15 02:17
@xPaw,

1. This is a cheap fix but yeah, I think it would always be better than `changed`!
2. Argh! Is there a cheap fix that can be made for this until we fix colored nicknames as a whole? It really looks like a regression at the moment :-(

Added 4.

**Comment by xPaw** [comment] 2016-02-15 08:59
@astorije 4 is because `#channel` sets the topic for you when you join it, `nick` is when it is actually changed while you're on the channel. It's not an issue.

**Comment by dubzi** [comment] 2016-02-15 14:57
Regarding point 2: I'd personally prefer a more toned down approach to quit/join messages (like you suggest in point 3). 
I'd go for actually showing nicks of quit/join in darkgrey even if you enable colored nicknames. They're not really saying anything, so there's no need to draw attention to them.

**Comment by astorije** [comment] 2016-02-15 15:06
> I'd go for actually showing nicks of quit/join in darkgrey even if you enable colored nicknames. They're not really saying anything, so there's no need to draw attention to them.

I'd argue with this that this is a visual reminder very much appreciated when skimming the page, it's nice to be able to mentally group a join followed by a message followed by a part/quit (too frequent, sadly...) for example.
Also, I find this a more accessible solution (as in [accessibility](https://en.wikipedia.org/wiki/Accessibility)).

Let me take a look at @xPaw's PR (#47) and I'll adapt/revoke my arguments.

**Comment by astorije** [comment] 2016-02-15 15:07
> @astorije 4 is because #channel sets the topic for you when you join it

Well damn, I was sure I could see who set the topic when joining a channel in my earlier HexChat days... My bad then.

**Comment by dgw** [comment] 2016-02-15 15:17
I definitely get "Set by" for the topic when joining a channel, at least on Rizon.

**Comment by dubzi** [comment] 2016-02-15 15:18
@astorije I missed #47. That's indeed how I prefer it. But then again, I also get your points.

**Comment by xPaw** [comment] 2016-02-15 18:00
About topics, the problem is that `slate-irc` bundles two different topic messages into same event, so there is no difference on our end. HexChat can properly display who set it and when because it correctly handles these events.

**Comment by astorije** [comment] 2016-02-16 01:29
Noted @xPaw.

**Closed** 2016-05-11 01:38 UTC
Labels: bug
