### ISSUE TITLE
notices on display at server linux not work.

### ISSUE THREAD

**Issue by blueeyedboy** [thelounge/lounge#1268] opened 2017-06-24 21:09 UTC
Here is a problem with notices display not work on linux server.?

when a client write notice to an other can see notice only at status. this is really no good?

wanna to know how can i fix it?

**Comment by dgw** [comment] 2017-06-24 21:15
I _think_ this is a duplicate of #114.

**Comment by blueeyedboy** [comment] 2017-06-24 21:22
dgw, I'm interest to fix issue? if i can how.?

**Comment by dgw** [comment] 2017-06-24 22:42
See the discussion in the linked issue. It's a change that would need to be made in the code, but the maintainers have not agreed on how/whether to change it.

**Closed** 2017-06-25 05:28 UTC
Labels: duplicate, enhancement
