### ISSUE TITLE
NaN:NaN as time for link toggle

### ISSUE THREAD

**Issue by michaelowens** [thelounge/lounge#514] opened 2016-07-18 11:19 UTC
As seen on screenshot:

![NaN:NaN](http://i.imgur.com/KT7h0za.png)

**Comment by YaManicKill** [comment] 2016-07-18 11:24
Are you on version 1.5.0 just now? This should be fixed on 2.0.0-pre4, hoping to release that soon.

**Comment by michaelowens** [comment] 2016-07-18 11:25
Ah yes, I got it off NPM which is 1.5.0. My bad!

**Closed by YaManicKill** 2016-07-18 11:24 UTC
Labels: duplicate, invalid

**Comment by YaManicKill** [comment] 2016-07-18 11:26
No problem :-) duplicate of #244
