### ISSUE TITLE
Update chat name in sidebar (and underlying window) when a user changes their nick 

### ISSUE THREAD

**Issue by henry158** [thelounge/lounge#596] opened 2016-09-08 08:34 UTC
I have come to this client from Irssi, and when a user in a query with yourself, if they change nicks the server follows that change and update see here for the the specific c file for how it is handled.

It would be nice to see this added, I have little to no (node)js experience at all or I'd do it myself.

I had a quick dig through the Irssi source, found where it is done... [here](https://github.com/irssi/irssi/blob/master/src/irc/core/irc-queries.c)

**Comment by xPaw** [comment] 2016-09-24 19:36
Duplicate of #337.

**Closed by xPaw** 2016-09-24 19:36 UTC
Labels: enhancement
