### ISSUE TITLE
Lounge crashes on joining a network (master/ff72ebb)

### ISSUE THREAD

**Issue by PolarizedIons** [thelounge/lounge#965] opened 2017-03-15 20:09 UTC
I tested this with private mode on, but it seems to also happen in public mode. 

Crash: https://hastebin.com/inucebezil.js

entire terminal session: https://hastebin.com/ijuzarusex.txt (tl;dr: cloned repo, installed, and removed .lounge config folder (so default configs) before running)

**Comment by MaxLeiter** [comment] 2017-03-16 16:15
Maybe change title to specify that it occurs when launching lounge, not just once its launched?

**Comment by PolarizedIons** [comment] 2017-03-17 11:30
@MaxLeiter well, it only happens on connecting (which would happen on startup) but it isn't the startup that is causing the crash.

**Comment by xPaw** [comment] 2017-03-17 14:50
Regressed since identd PR was merged, will take a look this weekend.

**Comment by xPaw** [comment] 2017-03-17 19:45
I am actually unable to reproduce this. But maybe these changes will fix the issue?
```diff
diff --git a/src/identification.js b/src/identification.js
index a3386cb..ea4cca2 100644
--- a/src/identification.js
+++ b/src/identification.js
@@ -30,10 +30,10 @@ class Identification {
 				var address = server.address();
 				log.info(`Identd server available on ${colors.green(address.address + ":" + address.port)}`);
 
-				startedCallback();
+				startedCallback(this);
 			});
 		} else {
-			startedCallback();
+			startedCallback(this);
 		}
 	}
 
diff --git a/src/plugins/irc-events/connection.js b/src/plugins/irc-events/connection.js
index fb2fdb7..84f4649 100644
--- a/src/plugins/irc-events/connection.js
+++ b/src/plugins/irc-events/connection.js
@@ -6,7 +6,6 @@ var Helper = require("../../helper");
 
 module.exports = function(irc, network) {
 	var client = this;
-	var identHandler = this.manager.identHandler;
 
 	network.channels[0].pushMessage(client, new Msg({
 		text: "Network created, connecting to " + network.host + ":" + network.port + "..."
@@ -65,7 +64,7 @@ module.exports = function(irc, network) {
 	let identSocketId;
 
 	irc.on("raw socket connected", function(socket) {
-		identSocketId = identHandler.addSocket(socket, client.name || network.username);
+		identSocketId = client.manager.identHandler.addSocket(socket, client.name || network.username);
 	});
 
 	irc.on("socket close", function() {
diff --git a/src/server.js b/src/server.js
index 347214c..636b5ab 100644
--- a/src/server.js
+++ b/src/server.js
@@ -13,7 +13,6 @@ var ldap = require("ldapjs");
 var colors = require("colors/safe");
 const Identification = require("./identification");
 
-let identHandler = null;
 var manager = null;
 var authFunction = localAuth;
 
@@ -89,7 +88,7 @@ in ${config.public ? "public" : "private"} mode`);
 
 	manager = new ClientManager();
 
-	identHandler = new Identification(() => {
+	new Identification((identHandler) => {
 		manager.init(identHandler, sockets);
 	});
 };
```

**Comment by MaxLeiter** [comment] 2017-03-17 20:10
I'll try this tomorrow when I have time; you tried on latest master with a user with networks/channels to auto join?

**Comment by xPaw** [comment] 2017-03-17 20:11
> you tried on latest master with a user with networks/channels to auto join?

Yap.

**Comment by MaxLeiter** [comment] 2017-03-17 20:16
Tried now, patch worked 👍

**Closed** 2017-03-18 00:56 UTC
Labels: bug
