### ISSUE TITLE
The Lounge is not loading, and `TypeError: a(...).textcomplete is not a function`

### ISSUE THREAD

**Issue by mortie** [thelounge/lounge#1665] opened 2017-10-26 11:11 UTC
I updated to The Lounge version 2.5.0 yesterday. Everything worked smoothly, but today, it just doesn't load. The network tab in the debugger looks fine, with just a bunch of 200 OK requests, but the abovementioned TypeError is in the JS console.

Here's a screenshot of how the whole page looks, including the stack trace in Firefox' debugger:

![](https://s.mort.coffee/d/img/scr-9016058.png)

**Comment by xPaw** [comment] 2017-10-26 11:11
Duplicate of #1647

**Closed by xPaw** 2017-10-26 11:11 UTC
