### ISSUE TITLE
Do not hide server sidebar burger button on desktop browsers

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#50] opened 2016-02-15 17:57 UTC
Currently the button is only visible on mobile devices, however it could be desirable to hide channels on desktop too.

**Comment by chanand** [comment] 2016-11-02 16:34
Should the title icon be removed? Or just show the button beside it?

**Comment by astorije** [comment] 2016-11-20 04:16
I'm not fond of this suggestion, @xPaw. I'd rather not have yet another menu button always shown on the app.
Also, not trying to emulate others, but none of the desktop (Mac) clients for Skype, Slack or Telegram offer a way to hide the channels when window width permits it.

**Comment by YaManicKill** [comment] 2016-12-20 14:47
Just realised this is a duplicate of #17

**Closed by YaManicKill** 2016-12-20 14:47 UTC
Labels: enhancement, up for grabs
