### ISSUE TITLE
App won't load on mobile data

### ISSUE THREAD

**Issue by PugaBear** [thelounge/lounge#768] opened 2016-11-28 18:11 UTC
https://imgur.com/a/XMFop

I'm pretty sure it works fine on wifi, its just when its on data. I am unfortunately unable to use remote debugging to debug it as my phone forgets the sim card every 2 minutes when I turn developer options on and requires a restart. 

Obviously its not a widespread problem otherwise there would already be an issue for this (I'm pretty sure I didn't miss it), but if anyone else is experiencing this and can debug it, I'd appreciate it tons. I'm on data 75% of the day and not having access to thelounge can sometimes be frustrating (I do have a mobile app and both connect to a znc instance but if I need some chat history I'm unable to access it) 

I'm on a samsung galaxy grand prime, android 5.1, latest chrome from app store. I also tested it on the default browser and got the same result.

**Comment by MaxLeiter** [comment] 2016-11-28 19:13
I'm not sure about a solution, possibly related to #421. Shouldn't znc keep your chat history so you can use another client though?

**Comment by PugaBear** [comment] 2016-11-28 19:23
thelounge steals it (because it is a constant connection to the bouncer), and I dont turn off the buffer clear cause it breaks my phone if I load the amount of messages I want to load...

PolarizedIons on IRC: loaded it up on my phone (with bad/slow wifi) and this showed up. Not sure if it is part of the issue though 
![image](https://cloud.githubusercontent.com/assets/12417961/20682465/c92a23c4-b56d-11e6-8b5e-c69334d60a8f.png)

**Comment by dgw** [comment] 2016-11-29 02:54
I use The Lounge mostly on mobile data with my instance, so I suspect a server configuration issue (especially given the 500 error in your follow-up screenshot of the JS console, @PugaBear).

My nginx config block is here:

````
  location / {
    proxy_http_version 1.1;
    proxy_set_header   X-Real-IP        $remote_addr;
    proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
    proxy_set_header   X-NginX-Proxy    true;
    proxy_set_header   Host             $http_host;
    proxy_set_header   Upgrade          $http_upgrade;
    proxy_redirect     off;
    proxy_pass         http://localhost:7688;
  }
````

**Comment by PugaBear** [comment] 2016-12-01 20:14
```
server {
    listen 80;
    server_name stafflounge.bn-mc.net;
    access_log off;
    error_log /var/log/nginx/stafflounge.bn-mc.net.error.log;
    root /dev/null;
    index index.html index.htm index.php;

    location / {
        proxy_http_version 1.1;
        proxy_set_header   X-Real-IP        $remote_addr;
        proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
        proxy_set_header   X-NginX-Proxy    true;
        proxy_set_header   Host             $http_host;
        proxy_set_header   Upgrade          $http_upgrade;
        proxy_redirect     off;
        proxy_pass         http://localhost:9000;
    }
}
```

I have that as my config (and even just freshly installed ubuntu16.04) but it still does not load.

**Comment by dgw** [comment] 2016-12-02 00:16
This is probably a silly question, because I'm sure you've done so already, @PugaBear …but have you checked for errors in `/var/log/nginx/stafflounge.bn-mc.net.error.log`?

I can't seem to find any error log created by The Lounge on my system, nor any options for configuring where its logs are stored in the docs… but if such a log exists (@thelounge/maintainers?) that'd be a good place to look too.

**Comment by PugaBear** [comment] 2016-12-02 01:40
Nothing appears in there when I load the page on mobile.

**Comment by PugaBear** [comment] 2016-12-07 15:15
I'm finally able to test thelounge on wifi and it turns out I'm experiencing exactly what is explained in the issue Max referenced above. Still unable to figure out a nginx configuration that solves this

**Comment by astorije** [comment] 2016-12-09 05:39
@PugaBear, can I mark this as duplicate of #421 then?

**Comment by xPaw** [comment] 2016-12-18 16:12
Can you try latest master and see if it's better/fixed?

**Comment by YaManicKill** [comment] 2016-12-20 16:07
Closing as duplicate of #421. 

#421 might be fixed, might still be an issue, but at the very least, this is a duplicate.

**Closed by YaManicKill** 2016-12-20 16:07 UTC
Labels: bug
