### ISSUE TITLE
Battery consumption on mobile phones

### ISSUE THREAD

**Issue by williamboman** [thelounge/lounge#651] opened 2016-09-28 12:49 UTC
The Lounge drains my battery extremely well on Chrome, Android (via "add to Home Screen" feature). I think it might be good to document possible battery consumption issues somewhere, alternatively investigate methods to decrease consumption.

**Comment by MaxLeiter** [comment] 2016-09-28 17:18
Drains my better on iOS as well; anyone have suggestions on analyzing the exact impact of Lounge?

**Comment by tmfksoft** [comment] 2016-10-13 01:23
Weinre may be of use. I can't remember if it can help with analyzing usage. But it may be of use. Although chrome dev with ADB etc may help. I may have a poke at it myself

**Comment by astorije** [comment] 2017-04-14 05:41
I haven't noticed this on my aging Android. @MaxLeiter @williamboman is that still an issue for you?

**Comment by MaxLeiter** [comment] 2017-04-14 16:59
It's still for-sure an issue; having any web-app like Lounge with websockets will have high consumption. However, even if we were to use the battery API or something, I don't see any easy fixes/optimizations for it (besides, for example, only fetching messages for channels when you switch to them or something)

**Comment by williamboman** [comment] 2017-04-15 19:51
> @williamboman is that still an issue for you?

I run iOS now, but I'm pretty sure the issue remains if you run TL via Add to Home Screen Chrome feature on Android.

**Comment by dgw** [comment] 2017-04-15 20:50
It does for me. I started using Atomic more often because of The Lounge battery consumption.

**Comment by dgw** [comment] 2017-04-21 04:43
The battery drain tonight was about 8% in 5-10 minutes on my Nexus 6. That's alarming.

**Comment by xPaw** [comment] 2017-04-21 06:13
#1041 could help here i think.

**Comment by YaManicKill** [comment] 2017-06-30 11:15
I'm going to close this as on it's own it's not really something we can "fix". There are a number of things that are caused by this, and we are working towards them. So this is just something we need to keep an eye on.

**Closed by YaManicKill** 2017-06-30 11:15 UTC
Labels: bug
