### ISSUE TITLE
Disconnections during load on mobile

### ISSUE THREAD

**Issue by dgw** [thelounge/lounge#1574] opened 2017-09-26 14:03 UTC
I have The Lounge pinned to my home screen on Android so it behaves like a pseudo-app, but when I open it there's a solid chance (in a small sample, over 50%) that once TL has loaded it will immediately go to its "Disconnected from server" mode (with the red banner/button above the input box) and need to be reloaded.

This has been the case on my device (Nexus 6 running Android 6.0.1) for a few months, at least. I also have heard from another user that loading The Lounge on his iPhone is a crap shoot, too. (Because of this, both of us tend to load native IRC apps instead of The Lounge to check things on our phones, because it's considerably faster.)

Anecdotally, I noticed the issue after "fixing" my nginx configuration some weeks ago so that the websocket transport would work (as tested in a desktop browser). TL had been using the polling transport without me noticing until I went poking around in dev tools to chase down (IIRC) a font issue. That said, I can recall the same thing happening before the configuration change.

Of course, reloading The Lounge on my phone until I get a solid, functional webapp does work; it just takes a few tries sometimes. I'm not sure if it's memory-related or something, but the fact that it's also occurring on iOS tells me that it isn't likely to be a side effect of my rooted & tweaked Android system. (I'm also pretty sure this is out of my current depth WRT Node apps in general and this codebase in particular, making this the first issue I've submitted in a while that I'm unlikely to submit a PR to fix myself.)

**Comment by xPaw** [comment] 2017-09-26 14:14
How many channels total do you have on your account?

**Comment by YaManicKill** [comment] 2017-09-26 14:14
This is bigger than a single issue, that is being fixed in a number of smaller ways.

#1471 will enable it to reconnect without reloading, meaning you don't get stuck in a loop. Meanwhile, #1145 encapsulates the need to only send 1 channel to start with.

**Comment by YaManicKill** [comment] 2017-09-26 14:19
Closing as duplicate of #1145

**Closed by YaManicKill** 2017-09-26 14:19 UTC
