### ISSUE TITLE
Display tooltips on user list and send buttons

### ISSUE THREAD

**Issue by astorije** [thelounge/lounge#188] opened 2016-03-13 05:32 UTC
Similarly to the bottom-left buttons, all icon buttons should have a tooltip.
I tried playing with the user list and gave up after realizing it would be more than a 1-minute fix :-)

**Comment by xPaw** [comment] 2016-05-28 11:27
Closed as a duplicate of #304.

**Closed by xPaw** 2016-05-28 11:27 UTC
Labels: enhancement

**Comment by astorije** [comment] 2016-05-28 18:38
Doh, how come I opened a dup of myself! Thanks for the catch @xPaw!
