### ISSUE TITLE
UI scaling

### ISSUE THREAD

**Issue by bews** [thelounge/lounge#1089] opened 2017-04-26 16:43 UTC
An idea to add UI scaling option in settings, because by default font and previews are too small for my display, which is very common (24" full hd): 
![2017-04-26_19-30-11](https://cloud.githubusercontent.com/assets/3627488/25445895/59933bc0-2ab8-11e7-9d71-71b18c0d2f3b.png)

So, it should work something like this:
* increase/decrease UI by percentage
* will affect font size in chat, title, user list (not sure about channel list - it looks fine)
* will affect site/picture preview size
* will affect some blocks width to fit bigger font

Any thoughts?

**Comment by williamboman** [comment] 2017-04-26 16:49
I think custom CSS should handle this quite well?

Try 

```
body {
  zoom: 1.2;
}
```

**Comment by MaxLeiter** [comment] 2017-04-26 16:50
related: #841

**Comment by bews** [comment] 2017-04-26 17:03
> zoom: 1.2;

No, it doesn't look good.

**Comment by bews** [comment] 2017-04-28 01:50
So, should we just increase font size or actually make UI scaling?

**Comment by astorije** [comment] 2017-04-28 22:43
> So, should we just increase font size or actually make UI scaling?

Increase font size.

UI scaling is very often an OS-wide setting and as an app, it should come with a sensible size similar to other apps. If The Lounge looks too small on a given monitor but is similar to other apps, then this must be solved by the user at a OS level (usually in accessibility settings).

Comparing to other apps, specifically chat apps I use, I think desktop size is OK but I wouldn't be against a 1px increase. However I also find the font size on mobile app too small compared to other apps.

Anyway, closing this as a duplicate of #841 then.

**Closed by astorije** 2017-04-28 22:43 UTC
