### ISSUE TITLE
Allow sending commands in lobby without slash

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#678] opened 2016-10-08 14:33 UTC

**Comment by astorije** [comment] 2016-10-08 16:45
Just for convenience? Wouldn't that be confusing or error-prone for the user if that becomes a habit?
I don't have a strong opinion, I'm just wondering.

**Comment by xPaw** [comment] 2016-10-08 16:47
Convenience, yes, but it might not be a good idea after all. Gotta compare how other clients do it.

**Comment by MaxLeiter** [comment] 2016-12-12 17:09
I don't think this is too good of an idea - no other clients do it afaik, and it could definitely lead to confusion/unexpected behavior for the user

**Comment by astorije** [comment] 2017-04-14 05:19
Another downside (at least for now until #706 makes it) is that since switching across channels keeps the same "message draft", one could accidentally post something in a channel instead of failing to send a command. I know I've done that before :)

Closing for now as we all have concerns about this.

**Closed by astorije** 2017-04-14 05:19 UTC
Labels: enhancement
